import '~/styles/globals.css';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';

import { ThemeProvider } from '~/components/theme/theme-provider';
import { TRPCReactProvider } from '~/trpc/react';

import { AppSidebar } from '~/components/app-sidebar';
import { ModeToggle } from '~/components/theme/theme-toggle';
import { Separator } from '~/components/ui/separator';
import {
    SidebarInset,
    SidebarProvider,
    SidebarTrigger,
} from '~/components/ui/sidebar';
import { HydrateClient } from '~/trpc/server';

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
    subsets: ['latin'],
    variable: '--font-geist-sans',
});

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html
            lang="en"
            className={`${geist.variable}`}
            suppressHydrationWarning
        >
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <TRPCReactProvider>
                        <SidebarProvider>
                            <AppSidebar />
                            <SidebarInset className="w-full">
                                <header className="flex h-16 items-center gap-2 justify-between w-full">
                                    <div className="flex items-center gap-2 px-4">
                                        <SidebarTrigger className="-ml-1" />
                                        <Separator
                                            orientation="vertical"
                                            className="mr-2 data-[orientation=vertical]:h-4"
                                        />
                                    </div>
                                    <div className="flex items-center gap-2 px-4">
                                        {/* <Separator
                            orientation="vertical"
                            className="mr-2 data-[orientation=vertical]:h-4"
                        /> */}
                                        <ModeToggle />
                                    </div>
                                </header>
                                <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                                    <HydrateClient>{children}</HydrateClient>
                                </div>
                            </SidebarInset>
                        </SidebarProvider>
                    </TRPCReactProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
